# frozen_string_literal: true

# Generated by epsalmond/codex .github/scripts/render-brew-formula.sh.
# Do not hand-edit: this file is overwritten by codex-fork-release CI on
# every published eric/local-features release.
#
# Source release: local-features-v0.159.1-main-r20261003004615.00000000000028e393216bd85d47
# Source commit (short): 00000000000028e393216bd85d47
class CodexShake < Formula
  desc "Eric/local-features fork build of Codex CLI, as codex-shake"
  homepage "https://github.com/epsalmond/codex"
  version "0.159.1.20261003004615"
  license "Apache-2.0"

  livecheck do
    skip "tap is updated by epsalmond/codex CI"
  end

  on_macos do
    on_arm do
      url "https://github.com/epsalmond/codex/releases/download/local-features-v0.159.1-main-r20261003004615.00000000000028e393216bd85d47/codex-aarch64-apple-darwin.tar.gz"
      sha256 "f46f9c8c4e4ea64684bbb0a5df93c54ff44f9180ddd523bd233d4efbb1bedecb"
    end
    on_intel do
      odie "codex-shake has no x86_64 macOS build"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/epsalmond/codex/releases/download/local-features-v0.159.1-main-r20261003004615.00000000000028e393216bd85d47/codex-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "149131b8e0caefc583e9745e66e115a93685e9915f3b0cc89c7321a967eff1b2"
    end
    on_arm do
      odie "codex-shake has no aarch64 Linux build"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"codex-shake").write_env_script libexec/"codex", PATH: "#{libexec}:$PATH"
    return unless File.exist?(libexec/"codex-shake-estimate")

    (bin/"codex-shake-estimate").write_env_script libexec/"codex-shake-estimate", PATH: "#{libexec}:$PATH"
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/codex-shake --version"))
  end
end
