# frozen_string_literal: true

# Generated by epsalmond/codex .github/scripts/render-brew-formula.sh.
# Do not hand-edit: this file is overwritten by codex-fork-release CI on
# every published eric/local-features release.
#
# Source release: local-features-v0.160.0-main-r20261004035011.00000000000028ec9b13d7371543
# Source commit (short): 00000000000028ec9b13d7371543
class CodexShake < Formula
  desc "Eric/local-features fork build of Codex CLI, as codex-shake"
  homepage "https://github.com/epsalmond/codex"
  version "0.160.0.20261004035011"
  license "Apache-2.0"

  livecheck do
    skip "tap is updated by epsalmond/codex CI"
  end

  on_macos do
    on_arm do
      url "https://github.com/epsalmond/codex/releases/download/local-features-v0.160.0-main-r20261004035011.00000000000028ec9b13d7371543/codex-aarch64-apple-darwin.tar.gz"
      sha256 "b1e499cd45728e8e7f8235a7e7b1361bfde4c3fd27e898e3f8251bd12f6a24bf"
    end
    on_intel do
      odie "codex-shake has no x86_64 macOS build"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/epsalmond/codex/releases/download/local-features-v0.160.0-main-r20261004035011.00000000000028ec9b13d7371543/codex-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "27380e6066f5a47400177f8325652df1d986d97629f3e6c9995b83aa8450d5e6"
    end
    on_arm do
      odie "codex-shake has no aarch64 Linux build"
    end
  end

  def install
    libexec.install Dir["*"]
    (bin/"codex-shake").write_env_script libexec/"codex", PATH: "#{libexec}:$PATH"
    return unless File.exist?(libexec/"codex-shake-estimate")

    (bin/"codex-shake-estimate").write_env_script libexec/"codex-shake-estimate", PATH: "#{libexec}:$PATH"
  end

  test do
    assert_match(/\d+\.\d+\.\d+/, shell_output("#{bin}/codex-shake --version"))
  end
end
